export const colors = {
  primary: "#735BF2",
  primaryLight: "#e1dbff",
  primaryDark: "#624DCF",
  primaryAlpha: "",
  secondary: "",
  secondaryDark: "#343434",
  secondaryLight: "",
  secondaryAlpha: "",
  neutral: "",
  neutralDark: "#cccccc",
  neutralDarker: "#a1a1a1",
  neutralLight: "#ebecf0",
  neutralLighter: "#f7f7f7",
  neutralAlpha: "",
  background: "#ffffff",
  textLight: "#ffffff",
  textDark: "#4A4A6B",
  error: "#FF0000",
  success: "#32CD32",
};
